apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
  - kind: ServiceAccount
    name: minio-operator
    {{- if .Values.namespace.create }}
    namespace: {{ .Values.namespace.name }}
    {{- end }}
