apiVersion: v1
kind: Service
metadata:
  name: "console"
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector:
    {{- include "minio-operator.console-selectorLabels" . | nindent 4 }}
