apiVersion: apps/v1
kind: Deployment
metadata:
  name: "minio-operator"
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: minio-operator
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
