apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
  labels:
{{ include "minio-operator.labels" . | nindent 4 }}
