{{ range .Values.tenants }}
{{- if .secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secrets.name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ .secrets.accessKey | b64enc }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ .secrets.secretKey | b64enc }}
{{- end }}
{{ end }}
