# Default values for minio-operator.

operator:
  image:
    repository: minio/operator
    tag: v4.0.1
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  image:
    repository: minio/console
    tag: v0.6.3
    pullPolicy: IfNotPresent
  replicaCount: 1
